### PR TITLE
Fix polarity of statement about RASA1 and NF1

### PR DESCRIPTION
**Pull request by bgyori**
I've been waiting for this for a long time! The PR fixes the polarity of four statements about NF1 and RASA1's regulation of HRAS/RAS Family. Here "enhancing catalytic activity" refers to the GTP-ase activity of RAS which _decreases_ its GTP-bound activity. Therefore the correct polarity here is directlyDecreases. There are further issues with this entry, namely that the actual evidence sentence, as cited doesn't correspond exactly to the one in the paper. In particular, in https://portlandpress.com/biochemsoctrans/article/34/5/846-850/65972, "RASA1 (p120-RASGAP)" is not actually there at the end of the sentence, the sentence continues with something else.

### CODE REVIEW

**Comment by bgyori** [comment]
Oh, and I'm not sure how to most efficiently generate the other files in the repo based on changes to the BEL script, do you have a script for that somewhere?

**Comment by bgyori** [comment]
I also looked at Travis, and it said "🔔 no BEL files changed", is that expected?

**Comment by cthoyt** [comment]
@bgyori hmm it seems that the branch didn't even get sent to travis :/

The most efficient way to update the pickle before merging is to cd into the directory and `pybel compile large_corpus-20170611.bel`. This will update the pickle right next to it and you can commit it as well. Otherwise, I will take care of it!

**Comment by bgyori** [comment]
Okay, I pushed the new pickle based on `pybel compile large_corpus-20170611.bel`

**Comment by cthoyt** [comment]
Look good now?

**Comment by bgyori** [comment]
Yes, I think so!

**Pull request merged**
